cookie:
  expiry_days: 30
  key: 06e375f8ccc68d94efea337199c6a29fae7d25c4f527b443cbeeba85a9852d47
  name: saint-inc_cookie_jar
credentials:
  usernames:
    saint:
      email: supremecrow999@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Saint-Inc
      password: $2b$12$AuBeKgqy0am0FwgwzstF/.iqaWX7QSoN0wPcwCM90tfa7BIdOex0K
pre-authorized:
  emails:
  - supremecrow999@gmail.com
